<style>
ul.messages li.warning {
    color: #FFCC44;
}

ul.messages li.error {
    color: #FF4444;
}
</style>

<h2><?php echo $this->escapeHtml($job->getName()) ?>: Complete</h2>
<h3>Messages</h3>
<ul class="messages">
<?php foreach ($messages as $message): ?>
<li class="<?php echo $this->escapeHtml($message->type . ' ' . $message->class) ?>">
    <?php echo $this->escapeHtml($message->text) ?></li>
<?php endforeach; ?>
</ul>